[build]
  base = "/web/"
  publish = ".next"
  command = "pnpm build"
[[plugins]]  
  package = "@netlify/plugin-nextjs"
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 301
  force = true