import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main id="main" className="main">
        Different Page
      </main>
      <footer id="footer" className="text-center">
        <div className="aside py-1">
          <div className="container-fluid">
            <p className="mb-1">
              * Produced while employed with Teneleven Interactive. © 2022
              Teneleven Interactive. Third party trademarks are registered
              trademarks of their respective&nbsp;owners.{' '}
              <span className="text-nowrap">All Rights Reserved.</span>
            </p>
          </div>
        </div>
        <div className="main py-3">
          <div className="container-fluid">
            <p className="m-0">
              © 2022 Cody McAfee. All Rights&nbsp;Reserved.
            </p>
          </div>
        </div>
      </footer>
      {/* <script src="./src/js/init.js" type="module"></script> */}

    </div>
  );
}
